# Generated by Django 3.0.4 on 2020-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=models.CharField(default=18222478938, max_length=32, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
